create table if not exists public.atlantica_products (
  id bigint generated by default as identity primary key,
  source_url text not null unique,
  nome text not null,
  categoria text,
  descricao text,
  imagem text,
  preco numeric(12,2),
  atualizado_em timestamptz not null default now()
);

create index if not exists atlantica_products_categoria_idx
  on public.atlantica_products (categoria);

alter table public.atlantica_products enable row level security;

create policy "catalogo publico leitura"
  on public.atlantica_products
  for select
  using (true);
